# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  BoergenerWebdesign\BwFeAdmin\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'


  BoergenerWebdesign\BwFeAdmin\EventListener\ModifyRecordListRecordActionsEventListener:
    tags:
      - name: event.listener
        identifier: 'bwfeadmin-modify-list-event'